name: Verificación de Enlaces Rotos

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar herramientas de verificación
        run: |
          npm install -g broken-link-checker
          sudo apt-get update
          sudo apt-get install -y lynx

      - name: Verificar enlaces y crear reporte
        id: link_check # Agregamos un ID a este paso para poder referenciar sus outputs
        run: |
          mkdir -p logs

          DOMAIN="https://chakielroms.com"
          LOG_FILE="logs/broken-links.log"
          DATE=$(date '+%Y-%m-%d %H:%M:%S UTC')
          BROKEN_LINKS_COUNT=0

          echo "=== VERIFICACIÓN DE ENLACES ROTOS - $DATE ===" > $LOG_FILE
          echo "" >> $LOG_FILE
          echo "🌐 Dominio verificado: $DOMAIN" >> $LOG_FILE
          echo "📅 Fecha de verificación: $DATE" >> $LOG_FILE
          echo "" >> $LOG_FILE

          # Verificar enlaces del sitio web en vivo y capturar los rotos
          if curl -s --head --max-time 10 "$DOMAIN" | head -n 1 | grep -q "200 OK"; then
            echo "🔍 Verificando enlaces en el dominio: $DOMAIN" >> $LOG_FILE
            
            # Usar broken-link-checker para escanear el sitio y guardar los resultados
            OUTPUT=$(blc -r -e -o --ignore-redirects "$DOMAIN" || true) # El '|| true' evita que el paso falle si encuentra enlaces rotos
            echo "$OUTPUT" >> $LOG_FILE
            
            # Contar los enlaces rotos
            BROKEN_LINKS_COUNT=$(echo "$OUTPUT" | grep -c "BROKEN")
          else
            echo "❌ El dominio $DOMAIN no responde con un estado 200 OK. No se puede verificar enlaces." >> $LOG_FILE
            BROKEN_LINKS_COUNT=1 # Consideramos un fallo si el dominio no está disponible
          fi

          echo "" >> $LOG_FILE
          echo "=== RESUMEN ===" >> $LOG_FILE
          echo "🚨 Total de enlaces rotos detectados: $BROKEN_LINKS_COUNT" >> $LOG_FILE
          echo "✅ Verificación completada: $DATE" >> $LOG_FILE

          # Creamos los outputs para usarlos en los siguientes pasos
          echo "broken_links_count=$BROKEN_LINKS_COUNT" >> $GITHUB_OUTPUT
          
      - name: Commit y push del reporte
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch origin
          git rebase origin/main || git rebase origin/master || echo "No rebase needed"
          git add logs/broken-links.log
          if git diff --staged --quiet; then
            echo "No hay cambios en el reporte de enlaces"
          else
            git commit -m "🔗 Reporte de enlaces rotos - $(date '+%Y-%m-%d %H:%M')"
            git push || {
              echo "Push failed, trying with rebase..."
              git pull --rebase origin main || git pull --rebase origin master
              git push
            }
          fi

      ---

      ## Envío de notificaciones a Discord

      - name: Notificación de éxito en Discord
        if: success() && steps.link_check.outputs.broken_links_count == '0'
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: |
            ✅ **Verificación de enlaces completada**
            
            No se encontraron enlaces rotos en **chakielroms.com**.
            
            **🔗 Log completo:** [`broken-links.log`](<${{ github.server_url }}/${{ github.repository }}/blob/main/logs/broken-links.log>)

      - name: Notificación de advertencias en Discord
        if: success() && steps.link_check.outputs.broken_links_count != '0'
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: |
            ⚠️ **Verificación de enlaces - Advertencias detectadas**
            
            Se encontraron **${{ steps.link_check.outputs.broken_links_count }}** enlaces rotos en **chakielroms.com**.
            
            **🔍 Revisa el log para más detalles:**
            **🔗 Log completo:** [`broken-links.log`](<${{ github.server_url }}/${{ github.repository }}/blob/main/logs/broken-links.log>)

      - name: Notificación de fallo en Discord
        if: failure()
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: |
            ❌ **¡Error en la verificación de enlaces!**
            
            La acción de verificación de enlaces para **chakielroms.com** falló durante la ejecución.
            
            **🔗 Ver detalles del error:**
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
