# Backup completo a MEGA
name: Backup a MEGA

on:
  schedule:
    # Ejecuta cada día a las 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Permite ejecutar manualmente

jobs:
  backup-to-mega:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repositorio actual
      uses: actions/checkout@v4
      with:
        fetch-depth: 1 # Solo el último commit
        
    - name: Configurar fecha y variables
      id: date
      run: |
        echo "date=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_OUTPUT
        echo "short_date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        echo "year=$(date +'%Y')" >> $GITHUB_OUTPUT
        echo "month=$(date +'%m-%B')" >> $GITHUB_OUTPUT
        echo "repo_name=chakielroms.com" >> $GITHUB_OUTPUT
        
    - name: Crear backup del código fuente
      id: create_backup
      run: |
        mkdir -p backup-data
        
        # Crear archivo comprimido SOLO del código fuente importante
        echo "📦 Creando backup de chakielroms.com..."
        tar -czf backup-data/chakielroms-backup-${{ steps.date.outputs.date }}.tar.gz \
          --exclude='.git' \
          --exclude='backup-data' \
          --exclude='node_modules' \
          --exclude='.github' \
          --exclude='*.log' \
          --exclude='*.tmp' \
          3ds/ android/ assets/ dmca/ gamecube/ \
          logs/ pc/ ps2/ ps3/ ps4/ psvita/ \
          sudachi/ wii/ wiiu/ \
          CNAME index.html robots.txt sitemap.xml styles.css
          
        # Obtener información del backup
        BACKUP_SIZE_HUMAN=$(du -h backup-data/chakielroms-backup-${{ steps.date.outputs.date }}.tar.gz | cut -f1)
        BACKUP_SIZE_BYTES=$(stat -f%z backup-data/chakielroms-backup-${{ steps.date.outputs.date }}.tar.gz 2>/dev/null || stat -c%s backup-data/chakielroms-backup-${{ steps.date.outputs.date }}.tar.gz)
        BACKUP_SIZE_MB=$((BACKUP_SIZE_BYTES / 1024 / 1024))
        
        echo "backup_size_human=$BACKUP_SIZE_HUMAN" >> $GITHUB_OUTPUT
        echo "backup_size_mb=$BACKUP_SIZE_MB" >> $GITHUB_OUTPUT
        echo "backup_filename=chakielroms-backup-${{ steps.date.outputs.date }}.tar.gz" >> $GITHUB_OUTPUT
        
        # Contar archivos incluidos
        TOTAL_FILES=$(tar -tzf backup-data/chakielroms-backup-${{ steps.date.outputs.date }}.tar.gz | wc -l)
        echo "total_files=$TOTAL_FILES" >> $GITHUB_OUTPUT
        
        echo "✅ Backup creado: $BACKUP_SIZE_HUMAN ($TOTAL_FILES archivos)"
        
    - name: Configurar MEGA CLI
      uses: Difegue/action-megacmd@master
      with:
        username: ${{ secrets.MEGA_USERNAME }}
        password: ${{ secrets.MEGA_PASSWORD }}
        
    - name: Crear estructura de carpetas en MEGA
      id: setup_mega
      run: |
        # Crear estructura jerárquica en MEGA
        REPO_NAME="${{ steps.date.outputs.repo_name }}"
        YEAR="${{ steps.date.outputs.year }}"
        MONTH="${{ steps.date.outputs.month }}"
        
        echo "📁 Configurando estructura en MEGA..."
        
        # Verificar y crear carpetas si no existen
        mega-mkdir -p "/GitHub-Backups" || echo "Carpeta principal ya existe"
        mega-mkdir -p "/GitHub-Backups/$REPO_NAME" || echo "Carpeta del sitio ya existe"
        mega-mkdir -p "/GitHub-Backups/$REPO_NAME/$YEAR" || echo "Carpeta del año ya existe"
        mega-mkdir -p "/GitHub-Backups/$REPO_NAME/$YEAR/$MONTH" || echo "Carpeta del mes ya existe"
        
        MEGA_PATH="/GitHub-Backups/$REPO_NAME/$YEAR/$MONTH"
        echo "mega_path=$MEGA_PATH" >> $GITHUB_OUTPUT
        
        echo "✅ Estructura creada: $MEGA_PATH"
        
    - name: Subir backup a MEGA
      id: upload_mega
      run: |
        MEGA_PATH="${{ steps.setup_mega.outputs.mega_path }}"
        BACKUP_FILE="backup-data/${{ steps.create_backup.outputs.backup_filename }}"
        
        echo "📤 Subiendo ${{ steps.create_backup.outputs.backup_size_human }} a MEGA..."
        echo "📍 Destino: $MEGA_PATH"
        
        # Subir archivo principal
        if mega-put "$BACKUP_FILE" "$MEGA_PATH/"; then
          echo "✅ Archivo subido exitosamente a MEGA"
          echo "upload_success=true" >> $GITHUB_OUTPUT
          
          # Intentar generar enlace público (opcional)
          echo "🔗 Generando enlace público..."
          PUBLIC_LINK=$(mega-export "$MEGA_PATH/${{ steps.create_backup.outputs.backup_filename }}" 2>/dev/null | grep -o 'https://mega.nz/file/[^[:space:]]*' || echo "")
          
          if [ -n "$PUBLIC_LINK" ]; then
            echo "public_link=$PUBLIC_LINK" >> $GITHUB_OUTPUT
            echo "✅ Enlace público generado"
          else
            echo "public_link=" >> $GITHUB_OUTPUT
            echo "ℹ️ Sin enlace público (normal)"
          fi
          
        else
          echo "❌ Error subiendo archivo a MEGA"
          echo "upload_success=false" >> $GITHUB_OUTPUT
          exit 1
        fi
        
    - name: Verificar subida y obtener información de MEGA
      id: verify_mega
      run: |
        MEGA_PATH="${{ steps.setup_mega.outputs.mega_path }}"
        
        echo "📋 Verificando archivos en MEGA..."
        
        # Listar archivos en la carpeta para verificar
        if mega-ls "$MEGA_PATH" | grep -q "${{ steps.create_backup.outputs.backup_filename }}"; then
          echo "✅ Archivo confirmado en MEGA"
          
          # Contar total de backups en la carpeta
          TOTAL_BACKUPS=$(mega-ls "$MEGA_PATH" | grep -c "chakielroms-backup-" || echo "1")
          echo "total_backups=$TOTAL_BACKUPS" >> $GITHUB_OUTPUT
          
          # Obtener información de cuota (si está disponible)
          QUOTA_INFO=$(mega-du 2>/dev/null | grep -E "(Used|Available)" | head -1 || echo "Información no disponible")
          echo "quota_info=$QUOTA_INFO" >> $GITHUB_OUTPUT
          
        else
          echo "❌ Archivo NO encontrado en MEGA"
          exit 1
        fi
        
    - name: Limpiar backups antiguos en MEGA
      run: |
        MEGA_PATH="${{ steps.setup_mega.outputs.mega_path }}"
        
        echo "🧹 Limpiando backups antiguos..."
        
        # Obtener lista de archivos de backup ordenados por fecha (más antiguos primero)
        BACKUP_FILES=$(mega-ls "$MEGA_PATH" | grep "chakielroms-backup-" | sort)
        
        if [ -n "$BACKUP_FILES" ]; then
          BACKUP_COUNT=$(echo "$BACKUP_FILES" | wc -l)
          
          # Mantener solo los últimos 10 backups
          if [ $BACKUP_COUNT -gt 10 ]; then
            FILES_TO_DELETE=$(echo "$BACKUP_FILES" | head -n $((BACKUP_COUNT - 10)))
            
            echo "$FILES_TO_DELETE" | while read -r backup_file; do
              if [ -n "$backup_file" ]; then
                echo "🗑️ Eliminando backup antiguo: $backup_file"
                mega-rm "$MEGA_PATH/$backup_file" || echo "⚠️ No se pudo eliminar $backup_file"
              fi
            done
            
            echo "✅ Limpieza completada (mantenidos últimos 10 backups)"
          else
            echo "ℹ️ No hay backups antiguos que eliminar ($BACKUP_COUNT backups)"
          fi
        fi
        
    # Notificación de éxito
    - name: Notificación de éxito a Discord
      if: success()
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        content: |
          ✅ **¡Backup a MEGA completado exitosamente!**
          
          **📊 Detalles del backup:**
          - **Sitio web**: `chakielroms.com`
          - **Fecha**: `${{ steps.date.outputs.short_date }}`
          - **Tamaño**: `${{ steps.create_backup.outputs.backup_size_human }}` (${{ steps.create_backup.outputs.backup_size_mb }} MB)
          - **Archivos**: `${{ steps.create_backup.outputs.total_files }}` archivos incluidos
          - **Backups en MEGA**: `${{ steps.verify_mega.outputs.total_backups }}` backups almacenados
          
          **📁 Ubicación en MEGA:**
          > `GitHub-Backups/chakielroms.com/${{ steps.date.outputs.year }}/${{ steps.date.outputs.month }}/`
          
          **📂 Archivo:**
          > `${{ steps.create_backup.outputs.backup_filename }}`
          
          ${{ steps.upload_mega.outputs.public_link && format('**🔗 Enlace directo:**
          > {0}', steps.upload_mega.outputs.public_link) || '' }}
          
          **💾 Cuota MEGA:**
          > ${{ steps.verify_mega.outputs.quota_info }}
          
          **🎮 Contenido incluido:**
          🕹️ Consolas: 3DS, Android, GameCube, PC, PS2, PS3, PS4, PS Vita, Wii, Wii U, Sudachi
          🌐 Web: index.html, styles.css, assets, CNAME, robots.txt, sitemap.xml
          📂 Extras: logs, dmca, subir
          
          ---
          *🤖 Accede a tu cuenta MEGA para descargar el backup*
        
    # Notificación de fallo
    - name: Notificación de fallo a Discord
      if: failure()
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        content: |
          ❌ **¡Error en backup a MEGA!**
          
          El backup de **chakielroms.com** ha fallado.
          
          **🔍 Posibles causas:**
          - Credenciales de MEGA incorrectas o expiradas
          - Cuota de almacenamiento de MEGA excedida (50GB)
          - Problemas de conexión con servidores de MEGA
          - Error en la creación del archivo comprimido
          
          **📋 Ver logs detallados:**
          > ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          
          **⚙️ Verificar configuración:**
          - Secret `MEGA_USERNAME` configurado correctamente
          - Secret `MEGA_PASSWORD` configurado correctamente
          - Secret `DISCORD_WEBHOOK_URL` activo
          
          ---
          *🤖 Revisar cuenta MEGA y intentar de nuevo*
